name: Python Application CI

on:
  pull_request:
    branches: [ "main" ]

jobs:
  quality:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    
    - name: Install pipenv
      run: |
        python -m pip install --upgrade pip
        pip install pipenv
    
    - name: Install dependencies
      run: |
        pipenv install --dev
    
    - name: Run pylint
      run: |
        pipenv run pylint src --fail-under=10.0
    
    - name: Run tests
      run: |
        pipenv run python -m pytest test/ -v --no-header 