name: Pytest

on:
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    name: Testing
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"
    
    - name: Install pipenv
      run: |
        python -m pip install --upgrade pip
        pip install pipenv
    
    - name: Install dependencies
      run: |
        pipenv --python 3.11
        pipenv run pip install customtkinter packaging pillow
        pipenv run pip install pytest pytest-cov
    
    - name: Run tests with coverage
      run: |
        pipenv run python -m pytest test/ -v --no-header --cov=src --cov-report=term-missing --cov-report=xml
    
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v5
      with:
        file: ./coverage.xml
        fail_ci_if_error: true 
        token: ${{ secrets.CODECOV_TOKEN }}